authors:
  kevindaffaarr:
    name: Kevin Daffa Arrahman
    description: Creator of Quantist.io
    avatar: https://www.arweave.net/4PUA7Juzm1Yr8uxeVZrLE2hha5UGRWoMxYp94J8JTuM
    url: https://kevin.quantist.io